const products = [
  {
    name: "Shirt",
    describe: "The luxury laundry pro",
    image: "/images/shirt.jpg",
    priceIroning: 6,
    priceLaundry: 20,
  },
  {
    name: "Sweater",
    describe: "The luxury laundry pro",
    image: "/images/sweater.jpg",
    priceIroning: 10,
    priceLaundry: 20,
  },
  {
    name: "Jacket",
    describe: "The luxury laundry pro",
    image: "/images/jacket.jpg",
    priceIroning: 30,
    priceLaundry: 20,
  },
  {
    name: "coat",
    describe: "The luxury laundry pro",
    image: "/images/Coat.webp",
    priceIroning: 30,
    priceLaundry: 20,
  },
  {
    name: "Dress",
    describe: "The luxury laundry pro",
    image: "/images/Dress.jpg",
    priceIroning: 18,
    priceLaundry: 20,
  },
  {
    name: "Jeans",
    describe: "The luxury laundry pro",
    image: "/images/Jeans.jpg",
    priceIroning: 8,
    priceLaundry: 20,
  },
  {
    name: "Shorts",
    describe: "The luxury laundry pro",
    image: "/images/Shorts.jpg",
    priceIroning: 6,
    priceLaundry: 20,
  },
  {
    name: "Suit",
    describe: "The luxury laundry pro",
    image: "/images/Suit.jpg",
    priceIroning: 50,
    priceLaundry: 20,
  },
  {
    name: "Tie",
    describe: "The luxury laundry pro",
    image: "/images/Tie.webp",
    priceIroning: 4,
    priceLaundry: 20,
  },
  {
    name: "Scarf",
    describe: "The luxury laundry pro",
    image: "/images/Scarf.jpg",
    priceIroning: 20,
    priceLaundry: 15,
  },
  {
    name: "Hat",
    describe: "The luxury laundry pro",
    image: "/images/Hat.jpg",
    priceIroning: 10,
    priceLaundry: 20,
  },
  {
    name: "Cap",
    describe: "The luxury laundry pro",
    image: "/images/Cap.jpg",
    priceIroning: 10,
    priceLaundry: 15,
  },
  {
    name: "Socks",
    describe: "The luxury laundry pro",
    image: "/images/Socks.jpg",
    priceIroning: 6,
    priceLaundry: 10,
  },
  {
    name: "Boots",
    describe: "The luxury laundry pro",
    image: "/images/boots2.jpeg",
    price: 30,
  },
  {
    name: "Sandals",
    describe: "The luxury laundry pro",
    image: "/images/sandales2.jpeg",
    price: 20,
  },
  {
    name: "Sneakers",
    describe: "The luxury laundry pro",
    image: "/images/sneaker2.jpeg",
    price: 30,
  },
  {
    name: "Pyjamas",
    describe: "The luxury laundry pro",
    image: "/images/Pyjamas.jpg",
    priceIroning: 15,
    priceLaundry: 35,
  },
  {
    name: "tapis",
    describe: "The luxury laundry pro",
    priceIroning: "/images/tapis.jpg",
    price: 120,
  },
  {
    name: "bed cover",
    describe: "The luxury laundry pro",
    image: "/images/bedcover.jpg",
    priceIroning: 40,
    priceLaundry: 80,
  },
];

export default products;
